spring.application.name=demo
Spring.datasource.url=jdbc:mysql://localhost:3306/userMapping_db
Spring.datasource.username=root
Spring.datasource.Password=Nitish@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
Spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=8c1a9fbf1ca6f02b04ef4d28cbd11c6d280c38819c18904581d1ef4fbaa6a6a1d819ae5a
Jwt.expirations=172800000
logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web.servlet=TRACE